export type Project = {
  id: string;
  name: string;
  language: string;
  file: string;
  description: string;
  link?: string;
};

const paragraph = (lines: string[]) => lines.join("\n");

export const projects: Project[] = [
    {
    id: "patchword",
    name: "PatchWord",
    language: "C",
    file: "main.c",
    link: "https://patchword.vercel.app",
    description: paragraph([
      '"PatchWord is a dictionary-driven word game with a distributed subword search engine.',
      '',
      'Core game loop:',
      '- Generates a starter substring and asks players to submit up to five valid dictionary words containing it',
      '- Scores total/longest words and surfaces the best possible matches in the dictionary',
      '',
      'Distributed mode:',
      '- Forks workers and coordinates them via a custom text-based IPC protocol (poll + SIGCHLD) to fan out substring searches',
      '- Aggregates worker results for batch subword queries',
      '',
      'Web/API wrapper:',
      '- C engine exposed through a FastAPI/uvicorn service with a bundled web UI',
      '- Packaged in Docker and hosted on Vercel for easy access',
      '',
      'Stack: C, FastAPI, Docker, Vercel."',
    ]),
  },
  {
    id: "defenseer",
    name: "DefenSeer",
    language: "Python",
    file: "main.py",
    link: "https://kwiskwis-defenseer.hf.space",
    description: paragraph([
      '"DefenSeer is an AI-augmented secure code runner for Python that combines sandboxed execution, static analysis, and ML triage to catch high-impact vulnerabilities while reducing false alarms.',
      '',
      'Workflow:',
      '- Upload or select a sample project and execute it in a CPU/memory-limited sandbox before scanning',
      '- Bandit runs against the executed file and feeds findings into a lightweight ensemble classifier that flags likely false positives and surfaces real issues',
      '- Each finding shows severity, rule labels, code snippets, and filters for rule ID, line, and confidence',
      '',
      'Security copilot features:',
      '- AI fixer rewrites only the vulnerable snippet using OpenAI and shows diff + patched preview before applying',
      '- Rule label overrides explain common Bandit IDs in plain language',
      '- Workspace isolation copies projects to temp directories to avoid mutating the originals',
      '',
      'Stack: Python, Streamlit, Bandit, scikit-learn, OpenAI API.',
      '',
      'Goal: Provide a fast "run -> scan -> fix" loop that keeps analysis safe while making triage and remediation smoother for small teams."',
    ]),
  },
  {
    id: "colorithm",
    name: "Colorithm",
    language: "Python",
    file: "main.py",
    link: "https://kwiskwis-colorithm.hf.space",
    description: paragraph([
      '"Colorithm reimagines how people interact with color. Traditional color pickers rely on hue wheels or basic complementarity — Colorithm goes further by leveraging AI-driven aesthetic reasoning.',
      '',
      'Using the Colormind deep learning model, it learns from thousands of examples in art, film stills, and photography to understand which colors feel right together rather than just matching mathematically.',
      '',
      'Users can:',
      '- Option 1: Pick 1–2 base colors to guide the palette',
      '- Option 2: Upload photos or artworks to extract refined palettes with balanced tones',
      '- Let the model generate 5 harmonious swatches based on learned style patterns',
      '',
      'Stack: Python, Streamlit, Pillow, Requests, Colormind API',
      '',
      'Goal: Make color exploration intuitive, creative, and accessible — bridging the gap between human taste and machine intelligence.',
      '',
      'Whether for fashion styling, home decor, art direction, or UI design, Colorithm helps creators find palettes that are not only technically balanced but emotionally resonant."',
    ]),
  },
  {
    id: "hexplore",
    name: "Hexplore",
    language: "Python",
    file: "main.py",
    description: paragraph([
      '"Hexplore is an interactive unified intelligent agent for navigating a hex-grid environment under increasing uncertainty. It demonstrates three different approaches to autonomous decision-making.',
      'Hexplore places one agent in a shared environment and shows how its behaviour changes when the world becomes deterministic, probabilistic, or completely unknown.',
      '',
      'The simulation highlights three core AI paradigms:',
      '',
      'Deterministic Planning (UCS/A*)',
      'The agent computes the lowest-cost path when every action behaves exactly as expected. This mode visualizes classical graph search expanding nodes, evaluating paths, and converging on an optimal solution.',
      '',
      'Stochastic Decision-Making (MDP Value & Policy Iteration)',
      'When actions can drift or produce multiple outcomes, the agent switches to MDP planning. It evaluates expected rewards, updates value functions, and produces stable policies that handle uncertainty built into the environment.',
      '',
      'Model-Free Learning (Q-Learning / SARSA)',
      'When transition probabilities and penalties are hidden, the agent must learn the environment from scratch. Through repeated interaction, it updates Q-values, balances exploration vs. exploitation, and gradually discovers an effective policy without any prior model.',
      '',
      'Users can:',
      '- Run each decision mode in the same hex-grid environment',
      '- Watch search, planning, and RL unfold through visual animations',
      '- Compare how the agent behaves as environmental assumptions change',
      '- Inspect value maps, policy arrows, and RL learning progress',
      '- Switch between deterministic, stochastic, and unknown dynamics in real time',
      '',
      'Stack: Python, FastAPI, Next.js',
      '',
      'Goal: To provide a clear, interactive way to observe how a single agent adapts its strategy as uncertainty increases—bridging classical search, stochastic planning, and reinforcement learning into a single, intuitive environment."',
    ]),
  },
];
